apiVersion: v1
kind: Namespace
metadata:
  name: jobman-service
  annotations:
    description: This namespace contains all the resources needed to run the Jobman webservice

---
apiVersion: v1
kind: Namespace
metadata:
  name: jobman-service-exec
  annotations:
    description: This namespace contains all the resources needed to run the jobs launched by Jobman, including the jobs themselves
---

apiVersion: v1
kind: ServiceAccount
metadata:
  # annotations:
  #   kubernetes.io/enforce-mountable-secrets: "true"
  name: jobman-serviceaccount
  namespace: jobman-service
  annotations:
    description: Service account to launch jobman under, needed to assign roles that allows access to resources in another namespace (where the jobs are actually launched)
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-jobman-serviceaccount
  namespace: jobman-service-exec
  annotations:
    description: Role from the namespace where the jobs are acttually launched, allowing Jobman to manage the jobs and their related resources
rules:
- apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - rbac.authorization.k8s.io
  resources: ["jobs", "pods", "configmaps", "pods/log", "pods/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups:
    - ""
  resources: ["events"]
  verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-jobman-serviceaccount
  namespace: jobman-service-exec
  annotations:
    description: Bind the Jobman's service account from its namespace to the role in the namespace where the jobs are launched
subjects:
- kind: ServiceAccount
  name: jobman-serviceaccount
  namespace: jobman-service
roleRef:
 kind: Role
 name: role-jobman-serviceaccount
 apiGroup: rbac.authorization.k8s.io

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-jobman-serviceaccount-configmap
  namespace: jobman-service
  annotations:
    description: Allows Jobman's service account to access configmaps, needed to access the jobs' queue that is managed by a cron job not jobman itself
rules:
- apiGroups:
        - ""
  resources: ["configmaps"]
  verbs: ["get"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-jobman-serviceaccount-configmap
  namespace: jobman-service
  annotations:
    description: Bind Jobman's service account to the role giving it access to configmaps, needed to access the jobs' queue that is managed by a cron job not jobman itself
subjects:
- kind: ServiceAccount
  name: jobman-serviceaccount
  namespace: jobman-service
roleRef:
 kind: Role
 name: role-jobman-serviceaccount-configmap
 apiGroup: rbac.authorization.k8s.io
 
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobman-k8s-logger-serviceaccount
  namespace: jobman-service
  annotations:
    description: Needed for the k8s-logger sidecar container launched with a job when logs are stored in a file
automountServiceAccountToken: false

---

apiVersion: v1
kind: Secret
metadata:
  name: jobman-k8s-logger-serviceaccount-secret
  namespace: jobman-service-exec
  annotations:
    kubernetes.io/service-account.name: jobman-k8s-logger-serviceaccount
    description: Predefined token for the service account of the k8s-logger sidecar container,  to be mounted manually in the sidecar
type: kubernetes.io/service-account-token

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-jobman-k8s-logger-serviceaccount
  namespace: jobman-service-exec
  annotations:
    description: Rights needed by the k8s-logger sidecar container of every job
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log", "pods/status"]
  verbs: ["get"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-jobman-k8s-logger-serviceaccount
  namespace: jobman-service-exec
  annotations:
    description: Binds the roles needed by the k8s-logger sidecar to its service account
subjects:
- kind: ServiceAccount
  name: jobman-k8s-logger-serviceaccount
  namespace: jobman-service
roleRef:
 kind: Role
 name: role-jobman-k8s-logger-serviceaccount
 apiGroup: rbac.authorization.k8s.io
 
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: webservice-config
  namespace: jobman-service
data:
  settings.json: paste_here_the_adapted_settings_json_for_the_web_service_found_in_src

  
---
    
apiVersion: v1
kind: Service
metadata:
  name: jobman-service
  namespace: jobman-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: api
  selector:
    app: jobman-service-deployment
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobman-service-logs
  namespace: jobman-service
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256M

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobman-service-deployment
  namespace: jobman-service
spec:
  selector:
    matchLabels:
      app: jobman-service-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jobman-service-deployment
    spec:
      priorityClassName: core-services
      nodeSelector:
        chaimeleon.eu/target: core-services
      serviceAccountName: jobman-serviceaccount
      containers:
      - image: jobman-service:2.2.7
        imagePullPolicy: Always
        name: jobman-service-deployment-container
        env:
        - name: SETTINGS_FILE
          value: /opt/jobman/settings.json
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "1"
        ports:
        - containerPort: 8080
          name: api
        volumeMounts:
          - name: logs
            mountPath: /var/log/jobman
          - name: webservice-configmap
            mountPath: /opt/jobman/settings.json
            subPath: settings.json
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: jobman-service-logs
        - name: webservice-configmap
          configMap:
            defaultMode: 420
            name: webservice-config

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: jobman-ingress
  namespace: jobman-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/enable-cors: 'true'
spec:
  rules:
    - host: <jobman_host>
      http:
        paths:
          - path: /jobman-service/
            pathType: Prefix
            backend:
              service:
                name: jobman-service
                port:
                  number: 8080
